### ISSUE TITLE
Buffer narrowing causes lint errors

### ISSUE THREAD

**Issue by morganwillcock** [jamescherti/flymake-ansible-lint.el#2]
When creating a temporary file from the current buffer, buffer narrowing is not removed. This means that what gets sent to the linter may not be valid as a configuration file while the buffer is narrowed.

I think it would be expected to send the entire buffer contents rather than just the narrowed region, and it is likely a minimal change to do that:

```diff
--- a/flymake-ansible-lint.el
+++ b/flymake-ansible-lint.el
@@ -259,7 +259,9 @@ Returns the path of the newly created temporary file."
                    (file-exists-p temp-file-path)))
         (setq counter (1+ counter)))
       (unless (file-exists-p temp-file-path)
-        (write-region (point-min) (point-max) temp-file-path nil 'quiet)
+        (save-restriction
+          (widen)
+          (write-region (point-min) (point-max) temp-file-path nil 'quiet))
         temp-file-path))))
 
 (flymake-ansible-lint--quickdef-backend flymake-ansible-lint-backend
```

**Comment by jamescherti** [comment]
Your pull request has been merged. Thank you for your contribution, @morganwillcock.
